update redis@ service template
sous-chefs/redisio pull request #440
Opened 2021-05-05 10:23 UTC by ariva07

# Description

Fixes listening on only loopback interface

## Issues Resolved

https://github.com/sous-chefs/redisio/issues/439

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-05-05 10:23 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-05-06 08:22 UTC, Xorima commented
Hey @ariva07 

Can you please add a changelog entry for this then we can get it merged and released? 

Thanks

2021-05-11 19:53 UTC, ramereth requested changes
Please don't add the version in the changelog. We have some automation that will do that once we merge it.

2021-05-11 19:53 UTC, ramereth commented on CHANGELOG.md
> +## 4.2.1 (2021-05-07)
```suggestion
## Unreleased
```

2021-05-12 13:24 UTC, ariva07 commented on CHANGELOG.md
> +## 4.2.1 (2021-05-07)
Thanks, fixed

2022-08-13 00:01 UTC, ramereth approved these changes

2022-08-13 00:01 UTC, merged

2022-08-13 00:01 UTC, kitchen-porter commented
Released as: [6.2.4](https://github.com/sous-chefs/redisio/releases/tag/6.2.4)